### ISSUE TITLE
Error: Process blocked for too long

### ISSUE THREAD

**Issue by dhowe** [kof/node-qunit#119]
I get the following errors when I run a group of test via node-qunit:

```
[20:50:10] Error: Command failed: /bin/sh -c ./node_modules/.bin/qunit -l "{ globalSummary: true, errors: true }" -c src/mylib.js -d src/mylib_lts.js src/mylib_dict.js -t "test/mylib-qunit-helpers.js" ./test/mylib-tests1.js ./test/mylib-tests2.js ./test/mylib-tests3.js
[Error: Process blocked for too long]

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
```
I see it referenced [here] (https://github.com/kof/node-qunit/pull/109), but I'm not sure of the status... Any info or a workaround would be great, as my tests now fail when I try to run them in node (though they are ok in phantomjs)

**Comment by kof** [comment]
See maxBlockDuration option if its normal for your task that you block the process for seconds - increase it.
